### ISSUE TITLE
Mixin's property overwritten

### ISSUE THREAD

**Issue by nmarshall23** [blainehansen/vue-async-properties#4]
If you have a components with either `asyncData` or `asyncComputed` properties, and add a mixin with the same property, the mixin's property will be overwritten.

This means if mixin foo has `asyncData.foo`, and component bar has `asyncData.bar`. Then `asyncData.foo` will not exist in the component at run time.

**Comment by blainehansen** [comment]
This should be an easy fix, Vue's already figured this out for us:
https://vuejs.org/v2/guide/mixins.html#Custom-Option-Merge-Strategies

A new release will be on the way shortly.
